[2022-03-06 04:31:00,557] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: spotify_dag.whole_spotify_etl manual__2022-03-06T04:30:52.628399+00:00 [queued]>
[2022-03-06 04:31:00,834] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: spotify_dag.whole_spotify_etl manual__2022-03-06T04:30:52.628399+00:00 [queued]>
[2022-03-06 04:31:00,838] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-06 04:31:00,839] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-03-06 04:31:00,839] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-06 04:31:00,915] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): whole_spotify_etl> on 2022-03-06 04:30:52.628399+00:00
[2022-03-06 04:31:00,955] {standard_task_runner.py:52} INFO - Started process 909 to run task
[2022-03-06 04:31:00,983] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'spotify_dag', 'whole_spotify_etl', 'manual__2022-03-06T04:30:52.628399+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/spotify_dag.py', '--cfg-path', '/tmp/tmpdt61g7xz', '--error-file', '/tmp/tmprf1ok7a_']
[2022-03-06 04:31:00,993] {standard_task_runner.py:77} INFO - Job 11: Subtask whole_spotify_etl
[2022-03-06 04:31:01,235] {logging_mixin.py:109} INFO - Running <TaskInstance: spotify_dag.whole_spotify_etl manual__2022-03-06T04:30:52.628399+00:00 [running]> on host 320d3876a6f4
[2022-03-06 04:31:02,068] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ing.jlllopezp@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spotify_dag
AIRFLOW_CTX_TASK_ID=whole_spotify_etl
AIRFLOW_CTX_EXECUTION_DATE=2022-03-06T04:30:52.628399+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-06T04:30:52.628399+00:00
[2022-03-06 04:31:04,531] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:31:06,946] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:31:11,356] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:31:15,194] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:31:18,078] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:31:20,810] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:31:22,797] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:31:24,769] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:31:26,752] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:31:28,777] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:31:30,700] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:31:33,236] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:31:35,705] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:31:38,731] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:31:42,693] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:31:44,563] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:31:46,734] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:31:49,068] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:31:50,692] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:31:54,663] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:31:58,586] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:32:02,190] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:32:05,685] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:32:09,279] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:32:13,605] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:32:19,054] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:32:22,607] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:32:25,694] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:32:28,754] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:32:31,952] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:32:34,821] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:32:39,357] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:32:44,217] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:32:45,035] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:32:45,752] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:32:51,180] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:32:51,788] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:32:52,497] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:32:53,115] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:32:54,532] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:32:55,531] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:32:56,799] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:32:57,515] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:32:58,545] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:32:59,154] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:32:59,662] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:00,549] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:01,869] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:02,732] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:03,859] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:06,008] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:07,563] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:08,257] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:08,544] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:09,795] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:11,423] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:11,746] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:12,834] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:13,987] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:14,602] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:16,191] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:16,826] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:17,435] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:18,073] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:18,383] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:19,477] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:20,626] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:21,305] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:21,986] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:23,270] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:23,892] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:24,615] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:25,856] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:26,683] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:27,438] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:27,775] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:28,557] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:29,175] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:29,585] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:30,188] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:30,907] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:32,170] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:35,631] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:36,367] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:37,716] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:39,436] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:40,197] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:40,911] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:42,457] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:43,836] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:44,792] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:45,681] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:46,757] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:48,159] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:49,804] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:51,559] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:52,724] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:54,439] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:57,274] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:33:59,319] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:34:01,405] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:34:03,329] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:34:05,044] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:34:09,067] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:34:10,096] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:34:10,711] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:34:11,241] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:34:12,274] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:34:14,723] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:34:16,714] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:34:18,951] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:34:23,979] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:34:25,953] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:34:27,966] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:34:30,678] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:34:32,216] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:34:36,211] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:34:42,030] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:34:45,930] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:34:47,956] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:34:49,922] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:34:51,907] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:34:55,963] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:34:58,711] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:35:00,903] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:35:04,071] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:35:06,855] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:35:09,006] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:35:11,837] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:35:16,992] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:35:21,913] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:35:26,064] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:35:31,828] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:35:36,982] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:35:41,212] {logging_mixin.py:109} INFO - here goes a new token
[2022-03-06 04:36:54,842] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 288, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 288, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/spotify_etl.py", line 59, in run_spotify_etl
    time=before_unix_timestamp), headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2022-03-06 04:36:55,536] {taskinstance.py:1282} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_dag, task_id=whole_spotify_etl, execution_date=20220306T043052, start_date=20220306T043100, end_date=20220306T043655
[2022-03-06 04:36:55,857] {standard_task_runner.py:92} ERROR - Failed to execute job 11 for task whole_spotify_etl
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 288, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 288, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/spotify_etl.py", line 59, in run_spotify_etl
    time=before_unix_timestamp), headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2022-03-06 04:36:56,118] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-06 04:36:56,820] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
